version: '3'
services:
  cest3:
    build:
        context: ..
        dockerfile: .Dockerfile
    image: cest3/api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,adress=*:5005 -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=elm3
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
        - ./docker/volume_mysql:/mnt/mysql